In [1]:
import pandas as pd

order_df = pd.read_csv('/Users/kraligan/chat_bot_SQL_project/data/orders.csv')
order_df.head()

,order_id,user_id,status,date_purchase,date_shipped,date_delivered
0,1,32,shipped,2024-05-25 22:27:26,2024-05-26 22:27:26,NaN
1,2,24,delivered,2024-05-06 12:57:32,2024-05-08 12:57:32,2024-05-22 12:57:32
2,3,17,delivered,2024-05-08 05:05:25,2024-05-09 05:05:25,2024-05-20 05:05:25
3,4,16,delivered,2024-05-18 20:38:31,2024-05-19 20:38:31,2024-05-29 20:38:31
4,5,6,delivered,2024-05-17 11:01:51,2024-05-18 11:01:51,2024-05-28 11:01:51

In [3]:
users_df = pd.read_csv('/Users/kraligan/chat_bot_SQL_project/data/users.csv')
users_df.head(n=10)

,user_id,first_name,last_name,joining_date,phone,email,address,city,zip_code
0,1,Ramona,Howell,2024-05-27 14:15:52,686855635,at@google.com,6096 Inceptos Ave,Le Puy-en-Velay,78971
1,2,Destiny,Hendrix,2024-01-19 11:07:01,678832573,mollis.non@aol.com,Ap #783-2387 Sodales Rd.,Niort,25744
2,3,Hadassah,May,2024-05-31 08:34:10,688426254,massa@protonmail.com,"P.O. Box 530, 2177 Aliquam Rd.",La Roche-sur-Yon,16789
3,4,Ashton,Frederick,2023-11-10 00:45:31,602567588,metus.eu@outlook.com,274-3674 Et Ave,Moulins,44466
4,5,Xander,Bradshaw,2024-02-04 07:54:50,607687245,justo.sit.amet@outlook.com,4586 Nunc St.,Ã‰pinal,88077
5,6,Ella,Hampton,2023-09-29 19:17:17,613555748,enim.non@outlook.com,885-5408 Ipsum Rd.,Sens,32551
6,7,Garrett,Rojas,2024-04-17 00:40:17,638252774,non@yahoo.com,"P.O. Box 506, 5903 Eleifend St.",Castres,57268
7,8,Justina,Davidson,2023-11-14 02:19:24,607133766,ad.litora.torquent@protonmail.com,7384 Ut Road,Bastia,75872
8,9,Brady,Hyde,2024-01-19 09:52:52,678782322,libero.et@protonmail.com,2809 Ut St.,Versailles,72124
9,10,Bruno,Mclean,2023-12-14 17:19:50,604464321,aliquam.enim@protonmail.com,"338-5655 Laoreet, Avenue",Colmar,65631